services:
  postgres:
    image: postgres:14-alpine
    restart: "no"
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: puggies
      POSTGRES_DB: puggies
